e.api.internal_server_error=システムエラーです
e.api.not_found=404エラーです
e.api.bad_request=bad request. {0}
e.api.resource_not_found=一致する情報は見つかりませんでした
e.api.resource_already_exists=既に存在します
e.api.aborted=競合を起こしています
e.sampleapi.unknown=予期せぬエラーが発生しました
e.sampleapi.application.not_found=404 error
e.sampleapi.application.bad_request=bad request. {0}
e.sampleapi.repository.resource_not_found={0}に一致する情報はありません
e.sampleapi.repository.konamon.connection_failed=接続エラー
e.sampleapi.repository.resource_already_exists={0}は既に存在します
e.sampleapi.repository.aborted={0}で競合しました